# Generated by Django 3.0.5 on 2020-04-14 15:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DomainFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_valid_from', models.DateTimeField()),
                ('flag_valid_to', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FQDN', models.CharField(help_text='Fully Qualified Domain Name', max_length=255, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9]+\\.[a-z0-9]{1,4}$', 'yourdomain.com only', 'Invalid Entry')])),
                ('date_created', models.DateTimeField()),
                ('date_expires', models.DateTimeField()),
                ('date_deletion', models.DateTimeField()),
                ('flag', models.ManyToManyField(to='domains.DomainFlag')),
            ],
        ),
    ]
