# Generated by Django 3.0.5 on 2020-04-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0002_domainflag_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainflag',
            name='type',
            field=models.CharField(choices=[('EXPIRED', 'Expired'), ('OUTZONE', 'Outzone'), ('DELETE_CANDIDATE', 'Delete Candidate')], default='EXPIRED', max_length=20),
        ),
    ]
