# Generated by Django 3.0.5 on 2020-04-14 22:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0003_auto_20200414_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='FQDN',
            field=models.CharField(help_text='Fully Qualified Domain Name', max_length=255, unique=True, validators=[django.core.validators.RegexValidator('^www+\\.[a-z0-9]+\\.[a-z0-9]{1,4}$', 'www.yourdomain.com only', 'Invalid Entry')]),
        ),
    ]
