# Generated by Django 3.0.5 on 2020-04-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0004_auto_20200414_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainflag',
            name='flag_valid_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='domainflag',
            name='flag_valid_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
